"""Add schedules table

Revision ID: 9c624815aac6
Revises: 93f501d8a7d8
Create Date: 2025-11-21 09:12:10.294223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9c624815aac6'
down_revision: Union[str, None] = '93f501d8a7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('pipeline_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('frequency', sa.String(length=50), nullable=False),
    sa.Column('cron_expression', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('start_date', sa.String(length=50), nullable=True),
    sa.Column('end_date', sa.String(length=50), nullable=True),
    sa.Column('next_run_at', sa.String(length=50), nullable=True),
    sa.Column('last_run_at', sa.String(length=50), nullable=True),
    sa.Column('total_runs', sa.Integer(), nullable=False),
    sa.Column('successful_runs', sa.Integer(), nullable=False),
    sa.Column('failed_runs', sa.Integer(), nullable=False),
    sa.Column('is_airflow_synced', sa.Boolean(), nullable=False),
    sa.Column('airflow_dag_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schedules_created_by'), 'schedules', ['created_by'], unique=False)
    op.create_index(op.f('ix_schedules_next_run_at'), 'schedules', ['next_run_at'], unique=False)
    op.create_index(op.f('ix_schedules_pipeline_id'), 'schedules', ['pipeline_id'], unique=False)
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_pipeline_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_next_run_at'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_created_by'), table_name='schedules')
    op.drop_table('schedules')
    # ### end Alembic commands ###
